frontend/config/routes.rb
Frontend::Engine.routes.draw do
  resources :products
end

frontend/app/controllers/frontend/application_controller.rb
module Frontend
  class ApplicationController < ActionController::Base
  end
end

frontend/app/controllers/frontend/products_controller.rb
require_dependency "frontend/application_controller"

module Frontend
  class ProductsController < ApplicationController
    before_action :set_product, only: [:show, :edit, :update, :destroy]

    # GET /products
    def index
      @products = Product.all
    end

    # GET /products/1
    def show
    end

    # GET /products/new
    def new
      @product = Product.new
    end

    # GET /products/1/edit
    def edit
    end

    # POST /products
    def create
      @product = Product.new(product_params)

      if @product.save
        redirect_to @product, notice: 'Product was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /products/1
    def update
      if @product.update(product_params)
        redirect_to @product, notice: 'Product was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /products/1
    def destroy
      @product.destroy
      redirect_to products_url, notice: 'Product was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def product_params
        params[:product]
      end
  end
end

frontend/app/helpers/frontend/application_helper.rb
module Frontend
  module ApplicationHelper
  end
end

frontend/app/helpers/frontend/email_signups_helper.rb
module Frontend
  module EmailSignupsHelper
  end
end

frontend/app/helpers/frontend/products_helper.rb
module Frontend
  module ProductsHelper
  end
end

frontend/app/views/frontend/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
	<td><%= product.title %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

frontend/app/views/layouts/frontend/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Frontend</title>
  <%= stylesheet_link_tag    "frontend/application", media: "all" %>
  <%= javascript_include_tag "frontend/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>